select
    claim_id,
    member_id,
    provider_id,
    payer_id,
    payer_type,
    primary_service_category as service_category,
    diagnosis_group,
    place_of_service,
    service_date,
    submission_date,
    cast(last_adjudicated_at as date) as adjudication_date,
    cast(first_paid_at as date) as payment_date,
    current_status,
    billed_amount,
    allowed_amount,
    header_paid_amount as paid_amount,
    case
        when billed_amount is null or billed_amount = 0 then null
        else header_paid_amount / billed_amount
    end as paid_to_billed_ratio,
    turnaround_days,
    payment_lag_days,
    days_in_inventory,
    event_count,
    denial_event_count,
    resubmission_count,
    last_event_type,
    is_open,
    is_adjudicated,
    is_currently_denied,
    ever_denied,
    is_denial_recovered,
    is_rework,
    is_first_pass_resolved,
    is_paid,
    is_adjudication_sla_breach,
    is_payment_sla_breach,
    is_paid_late,
    is_kpi_eligible,
    has_invalid_billed_amount,
    has_missing_member_id,
    has_paid_gt_billed,
    is_duplicate_extract
from {{ ref('int_claim_lifecycle') }}
